# DS Damping gains
passiveDS:
  dampingTopic:
    # left : "/iiwa1/CustomControllers/controllers/PassiveDS/params" # "/control/lambda_Pos" #
    # right: "/iiwa_blue/CustomControllers/controllers/PassiveDS/params" #"/control/lambda_Pos" #
    left : "/control/lambda_Pos" #
    right: "/control/lambda_Pos" #

# object
object:
  mass : 1.0
  dimension:    [0.20, 0.20, 0.20]
  graspOffset:  [0.00, 0.00, 0.02]


# End-effector tool # left real : 0.175 # right real : 0.20
tool:
  offset2end_effector:
    left:  0.115 #0.175
    right: 0.115 #0.20

#
desVimp:   0.5
desVreach: 1.0
# tossing task parameters
tossing:
  desVtoss:           0.9
  releasePos:         [0.70, -0.00, 0.60] #[0.70, 0.00, 0.60] 0.65, -0.00, 0.65
  releaseOrient:      [1.00, 0.00, 0.00, 0.00]
  releaseLinVel_dir:  [1.00, 0.00, 1.00]
  releaseAngVel:      [0.00, 0.00, 0.00]
  restPos:            [0.50, 0.15, 0.30]
  restOrient:         [1.00, 0.00, 0.00, 0.00] 

# robot home pose
standby_pose:
  robot_left:
    position:    [0.35,  0.20, 0.80]
    orientation: [0.3827, -0.9239, 0.0, 0.0]
  robot_right:
    position:    [0.35,  -0.20, 0.80]
    orientation: [0.3827, 0.9239, 0.0, 0.0]

# Bimanual DS gains
ds_absolute_gains: [1.5, 1.5, 1.5, 1.0, 1.0, 1.0] # 2.5 orient [2.25, 2.25, 2.25, 1.0, 1.0, 1.0] #
ds_relative_gains: [2.0, 2.0, 2.0, 1.0, 1.0, 1.0]

# impact direction (angle in degree)
impact_direction:
  friction_angle: 20 #36
  max_friction_angle: 40
  impact_dir_preset: false

# dual arm task
dual_arm_task:
  dualTaskSelector: 1
  old_dual_method: false
  modulated_reaching: true
  isNorm_impact_vel: false
  isQP_wrench_generation: true
  lifting: 
    position: [0.40, 0.00, 0.60] #[0.45, 0.00, 0.70] z0.6
    orientation: [1.00, 0.00, 0.00, 0.00]
  placing: 
    position: [0.675, 0.0, 0.40]
    orientation: [1.00, 0.00, 0.00, 0.00]
    height_via_point: 0.25