# DS Damping gains
passiveDS:
  dampingTopic:
    left : "/iiwa1/CustomControllers/controllers/PassiveDS/params" # "/control/lambda_Pos" #
    right: "/iiwa_blue/CustomControllers/controllers/PassiveDS/params" #"/control/lambda_Pos" #
    # left : "/iiwa1/control/lambda_Pos" #
    # right: "/iiwa_blue/control/lambda_Pos" #

# object
object:
  mass : 1.0
  dimension:       [0.20, 0.20, 0.20] #[0.26, 0.26,  0.26] #[0.20, 0.30, 0.20] #[0.16, 0.29, 0.14] # 
  graspOffset:     [-0.0, 0.00, -0.02] #[-0.04, 0.00,-0.035] #[0.00, 0.00, 0.00] #

  cubicBox :       [0.26, 0.26, 0.26]
  coronaBottePack: [0.13, 0.19, 0.14] 
  openBox:         [0.20, 0.30, 0.20]
  bottlesPack:     [0.25, 0.19, 0.20]
  drGabsPack:      [0.13, 0.14, 0.15]
  smallOpenBox:    [0.16, 0.29, 0.14]


# End-effector tool
tool:
  offset2end_effector:
    left:   0.115   # 0.175 #
    right:  0.115   # 0.20 #

#
desVimp:   0.4
desVreach: 1.0
# tossing task parameters
tossing:
  desVtoss:           0.9
  releasePos:         [0.70, 0.00, 0.60] #[0.70, 0.00, 0.60] [0.70, 0.00, 0.40]
  releaseOrient:      [1.00, 0.00, 0.00, 0.00]
  releaseLinVel_dir:  [1.00, 0.00, 1.00]
  releaseAngVel:      [0.00, 0.00, 0.00]
  restPos:            [0.50, 0.15, 0.30]
  restOrient:         [1.00, 0.00, 0.00, 0.00] 
  increment_release_pos: false

# robot home pose
standby_pose:
  robot_left:
    position:    [0.35,  0.20, 0.80]
    orientation: [0.3827, -0.9239, 0.0, 0.0]
  robot_right:
    position:    [0.35,  -0.20, 0.80]
    orientation: [0.3827, 0.9239, 0.0, 0.0]

# Bimanual DS gains
ds_absolute_gains: [1.5, 1.5, 1.5, 1.0, 1.0, 1.0] # 2.5 orient [2.25, 2.25, 2.25, 1.0, 1.0, 1.0] #
ds_relative_gains: [2.0, 2.0, 2.0, 1.0, 1.0, 1.0]

# impact direction (angle in degree)
impact_direction:
  friction_angle: 20 #36
  max_friction_angle: 40
  impact_dir_preset: false

# dual arm task
dual_arm_task:
  dualTaskSelector: 3
  old_dual_method: false
  modulated_reaching: true
  isNorm_impact_vel: false
  isQP_wrench_generation: true
  lifting: 
    position: [0.40, 0.00, 0.50] #[0.45, 0.00, 0.70]
    orientation: [1.00, 0.00, 0.00, 0.00]
    increment_lift_pos: false
  placing: 
    position: [0.72, 0.0, 0.25] #[0.675, 0.0, 0.25]  [0.72, 0.0, 0.25]
    orientation: [1.00, 0.00, 0.00, 0.00]
    height_via_point: 0.10
# converyor-belt
conveyor_belt:
  control_mode: true